kind: pipeline
name: Build (Arch)

platform:
  os: linux
  arch: amd64

steps:
- name: Fetch Submodules
  image: alpine/git
  commands:
  - git submodule init
  - git submodule update --recursive

- name: Build (Ubuntu Linux)
  image: abcminiuser/docker-ci-arm-toolchain:latest
  pull: always
  commands:
  - make -j -C left DEBUG=1
  - make -j -C left DEBUG=0
  - make -j -C right/uhk60v1 DEBUG=1
  - make -j -C right/uhk60v1 DEBUG=0
  - make -j -C right/uhk60v2 DEBUG=1
  - make -j -C right/uhk60v2 DEBUG=0
  - make -j -C keycluster DEBUG=1
  - make -j -C keycluster DEBUG=0
  - make -j -C trackball DEBUG=1
  - make -j -C trackball DEBUG=0
  - make -j -C trackpoint DEBUG=1
  - make -j -C trackpoint DEBUG=0
