manifest:
  self:
    path: device
    west-commands: scripts/west-commands.yml
  remotes:
    - name: sdk
      url-base: https://github.com/nrfconnect
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos
    - name: IntergatedCircuits
      url-base: https://github.com/IntergatedCircuits

  projects:
    - name: sdk-nrf
      remote: sdk
      path: nrf
      revision: v2.8.0
      import:
        path-prefix: nrfconnect
      clone-depth: 1
      import:
        name-allowlist:
          - zephyr
          - cmsis
          - hal_nordic
          - mcuboot
          - nrfxlib
          - lvgl
          - segger
          - tinycrypt
          - zcbor

    - name: hal_nxp
      remote: zephyr
      clone-depth: 1

    - name: c2usb
      remote: IntergatedCircuits
      revision: da4ad86f1cd3a4f8b42aa2d9acdd43e384341ce4
      clone-depth: 1
