#ifndef __SYSTEM_PROPERTIES_H__
#define __SYSTEM_PROPERTIES_H__

// Macros:

    #define SYSTEM_PROPERTY_USB_PROTOCOL_VERSION      1
    #define SYSTEM_PROPERTY_BRIDGE_PROTOCOL_VERSION   1
    #define SYSTEM_PROPERTY_DATA_MODEL_VERSION        1
    #define SYSTEM_PROPERTY_FIRMWARE_VERSION          1

#endif
