#ifndef __DEVICE_H__
#define __DEVICE_H__

// Macros:

    #define DEVICE_ID_UHK60V1 1
    #define DEVICE_ID_UHK60V2 2

    #define DEVICE_COUNT 5



#ifndef DEVICE_ID
    #error "DEVICE_ID is undefined!"
#endif

#if !(DEVICE_ID == DEVICE_ID_UHK60V1 || DEVICE_ID == DEVICE_ID_UHK60V2)
    #error "DEVICE_ID is invalid! See shared/device.h for valid values."
#endif


// TODO: unify this file with uhk80 device.h?
#ifndef CONFIG_DEVICE_ID
    #define CONFIG_DEVICE_ID DEVICE_ID
#endif

    #define DEVICE_ID_UHK60V1_RIGHT 1
    #define DEVICE_ID_UHK60V2_RIGHT 2
    #define DEVICE_ID_UHK80_LEFT 3
    #define DEVICE_ID_UHK80_RIGHT 4
    #define DEVICE_ID_UHK_DONGLE 5

    #define DEVICE_IS_UHK60V1_RIGHT (CONFIG_DEVICE_ID == DEVICE_ID_UHK60V1_RIGHT)
    #define DEVICE_IS_UHK60V2_RIGHT (CONFIG_DEVICE_ID == DEVICE_ID_UHK60V2_RIGHT)
    #define DEVICE_IS_UHK80_LEFT (CONFIG_DEVICE_ID == DEVICE_ID_UHK80_LEFT)
    #define DEVICE_IS_UHK80_RIGHT (CONFIG_DEVICE_ID == DEVICE_ID_UHK80_RIGHT)
    #define DEVICE_IS_UHK_DONGLE (CONFIG_DEVICE_ID == DEVICE_ID_UHK_DONGLE)

    #define DEVICE_IS_UHK80 (DEVICE_IS_UHK80_LEFT || DEVICE_IS_UHK80_RIGHT)
    #define DEVICE_IS_UHK60 (DEVICE_IS_UHK60V1_RIGHT || DEVICE_IS_UHK60V2_RIGHT)
    #define DEVICE_IS_MASTER (DEVICE_IS_UHK80_RIGHT || DEVICE_IS_UHK60V1_RIGHT || DEVICE_IS_UHK60V2_RIGHT)


#if DEVICE_IS_UHK60V1_RIGHT || DEVICE_ID_UHK60V2_RIGHT
    #define DEVICE_HAS_SEGMENT_DISPLAY 1
#else
    #define DEVICE_HAS_SEGMENT_DISPLAY 0
#endif

    typedef enum {
        DeviceId_Uhk60v1_Right = DEVICE_ID_UHK60V1_RIGHT,
        DeviceId_Uhk60v2_Right = DEVICE_ID_UHK60V2_RIGHT,
        DeviceId_Uhk80_Right = DEVICE_ID_UHK80_RIGHT,
        DeviceId_Uhk80_Left = DEVICE_ID_UHK80_LEFT,
        DeviceId_Uhk_Dongle = DEVICE_ID_UHK_DONGLE,
        DeviceId_Count = DEVICE_ID_UHK_DONGLE + 1,
    } device_id_t;

#endif
