#ifndef __USB_GENERIC_HID_DESCRIPTORS_H__
#define __USB_GENERIC_HID_DESCRIPTORS_H__

// Macros:

    #define USB_GENERIC_HID_CLASS (0x03U)
    #define USB_GENERIC_HID_SUBCLASS (0x00U)
    #define USB_GENERIC_HID_PROTOCOL (0x00U)

    #define USB_GENERIC_HID_INTERFACE_INDEX (2U)
    #define USB_GENERIC_HID_INTERFACE_COUNT (1U)
    #define USB_GENERIC_HID_INTERFACE_ALTERNATE_SETTING (0U)

    #define USB_GENERIC_HID_ENDPOINT_IN_ID (3U)
    #define USB_GENERIC_HID_ENDPOINT_OUT_ID (4U)
    #define USB_GENERIC_HID_ENDPOINT_COUNT (2U)

    #define USB_GENERIC_HID_INTERRUPT_IN_PACKET_SIZE (64U)
    #define USB_GENERIC_HID_INTERRUPT_IN_INTERVAL (0x04U)
    #define USB_GENERIC_HID_INTERRUPT_OUT_PACKET_SIZE (64U)
    #define USB_GENERIC_HID_INTERRUPT_OUT_INTERVAL (0x04U)

    #define USB_GENERIC_HID_REPORT_DESCRIPTOR_LENGTH (33U)
    #define USB_GENERIC_HID_STRING_DESCRIPTOR_LENGTH (38U)

// Variables:

    extern usb_device_class_struct_t UsbGenericHidClass;
    extern uint8_t UsbGenericHidReportDescriptor[USB_GENERIC_HID_REPORT_DESCRIPTOR_LENGTH];
    extern uint8_t UsbGenericHidString[USB_GENERIC_HID_STRING_DESCRIPTOR_LENGTH];

#endif
