#ifndef __OLED_DISPLAY_H__
#define __OLED_DISPLAY_H__

// Macros:

    #define DISPLAY_WIDTH 256
    #define DISPLAY_HEIGHT 64

    #define DISPLAY_SHIFTING_MARGIN 4

    #define DISPLAY_USABLE_WIDTH (DISPLAY_WIDTH-DISPLAY_SHIFTING_MARGIN)
    #define DISPLAY_USABLE_HEIGHT (DISPLAY_HEIGHT-DISPLAY_SHIFTING_MARGIN)

#endif // __OLED_DISPLAY_H__
