#ifndef __UART_DEFS_H__
#define __UART_DEFS_H__

// Includes:

    #include "attributes.h"
    #include <stdint.h>
    #include <stdbool.h>
    #include "crc16.h"

// Macros:


    // modules have very limited RAM, so keep low; Also, keep it
    #define UART_MAX_MODULE_PAYLOAD_LENGTH SLAVE_PROTOCOL_MAX_PAYLOAD_LENGTH
    // 244 = max BLE payload length
    #define UART_MAX_BRIDGE_PAYLOAD_LENGTH 244

    #define UART_CRC_LEN 2

    #define UART_LINK_SLOTS 1
    #define UART_LINK_CRC_BUF_LEN 4
    #define UART_LINK_START_END_BYTE_LEN 2

    #define UART_MAX_SERIALIZED_LENGTH(PAYLOAD_LENGTH) (PAYLOAD_LENGTH*2 + UART_LINK_START_END_BYTE_LEN + UART_LINK_CRC_BUF_LEN)

    #define UART_MAX_BRIDGE_SERIALIZED_MESSAGE_LENGTH UART_MAX_SERIALIZED_LENGTH(UART_MAX_BRIDGE_PAYLOAD_LENGTH)
    #define UART_MAX_MODULE_SERIALIZED_MESSAGE_LENGTH UART_MAX_SERIALIZED_LENGTH(UART_MAX_MODULE_PAYLOAD_LENGTH)
    #define UART_MAX_SERIALIZED_MESSAGE_LENGTH MAX(UART_MAX_BRIDGE_SERIALIZED_MESSAGE_LENGTH, UART_MAX_MODULE_SERIALIZED_MESSAGE_LENGTH)

    #define UART_BRIDGE_TIMEOUT 500

    #define UART_MODULE_PING_INTERVAL_MS 500
    #define UART_MODULE_TIMEOUT_MS (UART_MODULE_PING_INTERVAL_MS*4)

#endif // __UART_DEFS_H__
