// Please do not edit this file by hand!
// It is to be regenerated by /scripts/generate-versions-h.js

#ifndef __VERSIONS_H__
#define __VERSIONS_H__

// Includes:

    #include "fsl_common.h"

// Typedefs:

    typedef struct {
        uint16_t major;
        uint16_t minor;
        uint16_t patch;
    } version_t;

// Variables:

    #define FIRMWARE_MAJOR_VERSION 8
    #define FIRMWARE_MINOR_VERSION 10
    #define FIRMWARE_PATCH_VERSION 2

    #define DEVICE_PROTOCOL_MAJOR_VERSION 4
    #define DEVICE_PROTOCOL_MINOR_VERSION 7
    #define DEVICE_PROTOCOL_PATCH_VERSION 0

    #define MODULE_PROTOCOL_MAJOR_VERSION 4
    #define MODULE_PROTOCOL_MINOR_VERSION 1
    #define MODULE_PROTOCOL_PATCH_VERSION 0

    #define USER_CONFIG_MAJOR_VERSION 4
    #define USER_CONFIG_MINOR_VERSION 2
    #define USER_CONFIG_PATCH_VERSION 0

    #define HARDWARE_CONFIG_MAJOR_VERSION 1
    #define HARDWARE_CONFIG_MINOR_VERSION 0
    #define HARDWARE_CONFIG_PATCH_VERSION 0

#endif
