#!/bin/bash

version="$1"

if [ -z "$version" ]; then
    echo "No version number is specified."
    exit 1
fi

releaseName=uhk-firmware-$version
releaseDir=/tmp/$releaseName
rightFirmwareFile=../right/build/uhk60-right_release/uhk-right.hex
leftFirmwareFile=../left/build/uhk60-left_release/uhk-left.bin

/opt/Freescale/KDS_v3/eclipse/kinetis-design-studio \
--launcher.suppressErrors \
-noSplash \
-application org.eclipse.cdt.managedbuilder.core.headlessbuild \
-import ../left/build \
-import ../right/build \
-cleanBuild uhk-left \
-cleanBuild uhk-right

chmod 644 $rightFirmwareFile $leftFirmwareFile
ls -l $rightFirmwareFile $leftFirmwareFile
rm -r $releaseDir
mkdir $releaseDir
cp $rightFirmwareFile $releaseDir
cp $leftFirmwareFile $releaseDir
cp package.json $releaseDir
tar -cvjSf $releaseName.tar.bz2 -C $releaseDir .
