#ifndef __USB_DESCRIPTOR_MEDIA_KEYBOARD_REPORT_H__
#define __USB_DESCRIPTOR_MEDIA_KEYBOARD_REPORT_H__

// Macros:

    #define USB_MEDIA_KEYBOARD_REPORT_DESCRIPTOR_LENGTH 23
    #define USB_MEDIA_KEYBOARD_MAX_KEYS 4

// Variables:

    extern uint8_t UsbMediaKeyboardReportDescriptor[USB_MEDIA_KEYBOARD_REPORT_DESCRIPTOR_LENGTH];

#endif
