#include "usb_api.h"
#include "usb_descriptor_system_keyboard_report.h"

uint8_t UsbSystemKeyboardReportDescriptor[USB_SYSTEM_KEYBOARD_REPORT_DESCRIPTOR_LENGTH] = {
    HID_RI_USAGE_PAGE(8, HID_RI_USAGE_PAGE_GENERIC_DESKTOP),
    HID_RI_USAGE(8, HID_RI_USAGE_GENERIC_DESKTOP_SYSTEM_CONTROL),
    HID_RI_COLLECTION(8, HID_RI_COLLECTION_APPLICATION),
        // System key
        HID_RI_REPORT_SIZE(8, 2),
        HID_RI_REPORT_COUNT(8, USB_SYSTEM_KEYBOARD_MAX_KEYS),
        HID_RI_LOGICAL_MINIMUM(8, 1),
        HID_RI_LOGICAL_MAXIMUM(8, 3),
        HID_RI_USAGE(8, 0x82),
        HID_RI_USAGE(8, 0x81),
        HID_RI_USAGE(8, 0x83),
        HID_RI_INPUT(8, HID_IOF_NO_PREFERRED_STATE | HID_IOF_NULLSTATE),
    HID_RI_END_COLLECTION(0),
};
