#ifndef __BLACKBERRY_TRACKBALL_H__
#define __BLACKBERRY_TRACKBALL_H__

// Includes:

    #include "slave_protocol.h"

// Macros:

    #define BLACKBERRY_TRACKBALL_LEFT_PORT PORTB
    #define BLACKBERRY_TRACKBALL_LEFT_GPIO GPIOB
    #define BLACKBERRY_TRACKBALL_LEFT_IRQ PORTB_IRQn
    #define BLACKBERRY_TRACKBALL_LEFT_CLOCK kCLOCK_PortB
    #define BLACKBERRY_TRACKBALL_LEFT_PIN 6

    #define BLACKBERRY_TRACKBALL_RIGHT_PORT PORTA
    #define BLACKBERRY_TRACKBALL_RIGHT_GPIO GPIOA
    #define BLACKBERRY_TRACKBALL_RIGHT_IRQ PORTA_IRQn
    #define BLACKBERRY_TRACKBALL_RIGHT_CLOCK kCLOCK_PortA
    #define BLACKBERRY_TRACKBALL_RIGHT_PIN 12

    #define BLACKBERRY_TRACKBALL_UP_PORT PORTB
    #define BLACKBERRY_TRACKBALL_UP_GPIO GPIOB
    #define BLACKBERRY_TRACKBALL_UP_IRQ PORTB_IRQn
    #define BLACKBERRY_TRACKBALL_UP_CLOCK kCLOCK_PortB
    #define BLACKBERRY_TRACKBALL_UP_PIN 2

    #define BLACKBERRY_TRACKBALL_DOWN_PORT PORTB
    #define BLACKBERRY_TRACKBALL_DOWN_GPIO GPIOB
    #define BLACKBERRY_TRACKBALL_DOWN_IRQ PORTB_IRQn
    #define BLACKBERRY_TRACKBALL_DOWN_CLOCK kCLOCK_PortB
    #define BLACKBERRY_TRACKBALL_DOWN_PIN 0

    #define BLACKBERRY_TRACKBALL_IRQ_HANDLER1 PORTA_IRQHandler
    #define BLACKBERRY_TRACKBALL_IRQ_HANDLER2 PORTB_IRQHandler

// Variables:

    extern pointer_delta_t BlackBerryTrackball_PointerDelta;

// Functions:

    void BlackberryTrackball_Init(void);

#endif
