#ifndef __MODULE_H__
#define __MODULE_H__

// Macros:

    #define I2C_ADDRESS_MODULE_FIRMWARE I2C_ADDRESS_LEFT_MODULE_FIRMWARE
    #define MODULE_PROTOCOL_VERSION 1
    #define MODULE_ID ModuleId_KeyClusterLeft
    #define MODULE_KEY_COUNT (KEYBOARD_MATRIX_ROWS_NUM * KEYBOARD_MATRIX_COLS_NUM)
    #define MODULE_POINTER_COUNT 1

#endif
